* Emacs Revolution 
:PROPERTIES:
:project-name: Emacs Revolution
:project-version: 0.7b
:END:

#+TAGS: N/A(n) INSTALLÉ(i) 

** Description
 Emacs-Revolution est une distribution modernisée d’Emacs 30.1,
 composée de paquets Lisp et d’outils complémentaires.
 Comme tout outil de développement, il offre l'auto-complétion,
 la détection d’erreurs, documentation, compilation, enregistrement vocal, assistance IA, etc..

 Les principales caractéristiques du projet sont sa légèreté, favorisant la rapidité,
 ainsi que sa simplicité, basée sur la composition d’outils complexes et modernes.

 Cet outil a pour but d'etre libre et communautaire.

** Fonctionnement

Le fichier .emacs du projet Emacs Revolution doit remplacer celui d'origine,
permettant l'exécution du projet lui-même se trouvant dans ~/.emacs.d/revolution/ par défaut,
le chemin sera modifiable dans les versions futures.
Pour une meilleur lisibilite et une documentation complete, le projet est ecrit
en org dans son enssemble, puis celui-ci s'exporte en elisp.
/Donc cela est inutile de modifier les fichiers .el se trouvant dans revolution,
car ceux-ci sont generer par org a la moindre differences avec le code d'origine/
Pour chaque mode majeur, un fichier de configuration lui est associé dans revolution/modes.

** Langages supportés

      | Langage               | Documentation | Syntaxe | Complétion | LSP Server |
      |-----------------------+---------------+---------+------------+------------|
      | Bash                  |               |         |            | X          |
      | c                     |               | X       |            | N/A        |
      | C++                   |               |         |            | X          |
      | C#                    |               |         |            |            |
      | CSS/LessCSS/SASS/SCSS |               |         |            | X          |
      | Texte                 |               |         |            | N/A        |
      | TypeScript            |               |         |            | N/A        |
      | GitHub Copilot        |               |         |            |            |
      | HTML                  | X             | X       | X          | X          |
      | Javascript/typescript | X             | X       | X          | X          |
      | Json                  | N/A           |         | X          | X          |
      | Lisp/elisp            | X             | X       | X          | X          |
      | Makefile-gmake        |               |         |            | N/A        |
      | Python                |               |         |            |            |
      | PHP                   |               | X       | X          | X          |
      | Glsl                  |               |         |            |            |
      | Org                   | X             | X       | X          | N/A        |
      | Xml                   |               |         |            |            |
      | Yaml                  |               |         |            |            |

** Objectif
*** VERSION 1.0 [3/8]

  + [X] Chargement du mode adéquate.
  + [X] Switch vers le mode elisp on-line pour les fichiers org lors de l'ecriture de ce langage.
  + [X] Tous les fichiers elisp doivent être généré depuis org à partir de init-revolution-mode.el.    
  + [ ] Fichier de Configuration [0/2]
    - [ ] function qui verifie si le fichier de configuration nommee XXXXX existe.
    - [ ] Si il n'existe pas affiche un buffer de presentation de Emacs-Revolution avec des parametres configurables. [0/6]
      * [ ] Chemin d'installation par defaut, modifiable.
      * [ ] Formulaire pour personnaliser les raccourcis.
      * [ ] Confirmer l'installation du package en mode radion on/off: npm install -g @emacs-eask/cli
      * [ ] Lier cette fonction au fichier de configuration emacs-revolution-check-org
      * [ ] Autoriser/Valider l'installation
      * [ ] Permettre le choix de la durée avant mise a jour.
  + [ ] *Docsgen*, /Documentation de votre code/ : [0/1]
    - [ ] La documentation est générée de manière interactive ou
      à l’aide d’un raccourci clavier. Une fois créée,
      elle est automatiquement enregistrée sous le nom du projet,
      dans le répertoire racine, avec l’extension .org,
      à l’intérieur d’un dossier dédié à la documentation:
      /.emacs.d/revolution/docs/
    - [ ] Utiliser one.el ou emacs-ssg pour emuler un server web
      diffusant la documention org en page web,
      accessible depuis un racourcis(+interactive) clavier.
  + [ ] Flux RSS [0/3]
    - [ ] elfeed
    - [ ] barre d'affichage en haut de la fenêtre.
    - [ ] shortkey pour switcher afficher/cacher
    - [ ] shortkey pour afficher un formulaire pour ajouter un flux RSS.
  + [-] Divers [2/5]
    - [X] Neotree verifier son installation.
    - [ ] Simplifier la création de nouveaux headers, peut-être proposer d'injecter l'URL de la boite pour laquelle le projet est développé.
    - [ ] elisp-demos
    - [ ] bug-hunter
    - [X] which-key
      * [X] Affiche les completions des shortcuts disponibles.
      * [X] Affiche les shortcuts dans une frame en mode colonne a droite de la fenêtre.
      * [X] Affiche les shortcuts du mode seulement en continue dans une frame en mode colonne a droite de la fenêtre.
    - [ ] calfw-org
    - [ ] multiple-cursors
    - [ ] flycheck-package
    - [ ] flycheck-posframe
    - [ ] el-fly-indent-mode
    - [ ] boxy-headings
    - [ ] posframe
    - [ ] le Header permet d'ajouter tous les utilisateur ayant modifié le fichier.
    - [ ] org-project-capture
    - [ ] org-sidebar

** Copyright
   Copyright © 2025 Pierre Schebath (alias Glider)

   Cette œuvre est sous licence Creative Commons Attribution -
   Pas d’Utilisation Commerciale 4.0 International (CC BY-NC 4.0).

   Vous êtes libre de :
    - Partager — copier et redistribuer le matériel sur tout support ou sous tout format
    - Adapter — remixer, transformer et créer à partir du matériel

   À condition que l'utilisation ne soit pas commerciale.

** Contact
   Email: contact@lugtech.fr
