* Emacs Revolution 
:PROPERTIES:
:project-name: Emacs Revolution
:project-version: 0.7b
:END:

#+TAGS: N/A(n) INSTALLÉ(i) 

** Description
 Emacs-Revolution est une distribution modernisée d’Emacs 30.1,
 composée de paquets Lisp et d’outils complémentaires.
 Comme tout outil de développement, il offre l'auto-complétion,
 la détection d’erreurs, documentation, compilation, enregistrement vocal, assistance IA, etc..

 Les principales caractéristiques du projet sont sa légèreté, favorisant la rapidité,
 ainsi que sa simplicité, basée sur la composition d’outils complexes et modernes.

 Cet outil a pour but d'etre libre et communautaire.

** Fonctionnement

Le fichier .emacs du projet Emacs Revolution doit remplacer celui d'origine,
permettant l'exécution du projet lui-même se trouvant dans ~/.emacs.d/revolution/ par défaut,
le chemin sera modifiable dans les versions futures.
Pour une meilleur lisibilite et une documentation complete, le projet est ecrit
en org dans son enssemble, puis celui-ci s'exporte en elisp.
/Donc cela est inutile de modifier les fichiers .el se trouvant dans revolution,
car ceux-ci sont generer par org a la moindre differences avec le code d'origine/
Pour chaque mode majeur, un fichier de configuration lui est associé dans revolution/modes.

** Langages supportés

      | Langage               | Documentation | Syntaxe | Complétion | LSP Server |
      |-----------------------+---------------+---------+------------+------------|
      | Bash                  |               |         |            | X          |
      | c                     |               | X       |            | N/A        |
      | C++                   |               |         |            | X          |
      | C#                    |               |         |            |            |
      | CSS/LessCSS/SASS/SCSS |               |         |            | X          |
      | Texte                 |               |         |            | N/A        |
      | TypeScript            |               |         |            | N/A        |
      | GitHub Copilot        |               |         |            |            |
      | HTML                  | X             | X       | X          | X          |
      | Javascript/typescript | X             | X       | X          | X          |
      | Json                  | N/A           |         | X          | X          |
      | Lisp/elisp            | X             | X       | X          | X          |
      | Makefile-gmake        |               |         |            | N/A        |
      | Python                |               |         |            |            |
      | PHP                   |               | X       | X          | X          |
      | Glsl                  |               |         |            |            |
      | Org                   | X             | X       | X          | N/A        |
      | Xml                   |               |         |            |            |
      | Yaml                  |               |         |            |            |

** Installation

#+BEGIN_SRC bash
$> git clone -b 1.0a https://github.com/Glider-P90/Emacs-Revolution.git
#+END_SRC

#+BEGIN_SRC bash
$> cd Emacs-Revolution && ./install
#+END_SRC

** Copyright
   Copyright © 2025 Pierre Schebath (alias Glider)

   Cette œuvre est sous licence Creative Commons Attribution -
   Pas d’Utilisation Commerciale 4.0 International (CC BY-NC 4.0).

   Vous êtes libre de :
    - Partager — copier et redistribuer le matériel sur tout support ou sous tout format
    - Adapter — remixer, transformer et créer à partir du matériel

   À condition que l'utilisation ne soit pas commerciale.

** Contact
   Email: contact@lugtech.fr
