(defvar std-modes-alist
  '(("c-mode"                (begin . "/**") (mid . " * ") (end . "**/"))
    ("c++-mode"              (begin . "/**") (mid . " * ") (end . " */"))
    ("css-mode"              (begin . "/**") (mid . " * ") (end . " */"))
    ("scss-mode"             (begin . "/**") (mid . " * ") (end . " */"))
    ("text-mode"             (begin . "/**") (mid . " * ") (end . " */"))
    ("javascript-mode"       (begin . "/**") (mid . " * ") (end . " */"))
    ("java-mode"             (begin . "/**") (mid . " * ") (end . "**/"))
    ("js-mode"               (begin . "/**") (mid . " * ") (end . "**/"))
    ("js2-mode"              (begin . "/**") (mid . " * ") (end . "**/"))
    ("js3-mode"              (begin . "/**") (mid . " * ") (end . "**/"))
    ("typescript-mode"       (begin . "/**") (mid . " * ") (end . " */"))
    ("go-mode"               (begin . "/*")  (mid . " * ") (end . " */"))
    ("scala-mode"            (begin . "/*")  (mid . " * ") (end . " */"))
    ("kotlin-mode"           (begin . "/*")  (mid . " * ") (end . " */"))
    ("swift-mode"            (begin . "/*")  (mid . " * ") (end . " */"))
    ("csharp-mode"           (begin . "/*")  (mid . " * ") (end . " */"))
    ("rust-mode"             (begin . "///") (mid . "/// ") (end . "///"))
    ("json-mode"             (begin . "//")  (mid . "// ") (end . "//"))
    ("mhtml-mode"            (begin . "<!--") (mid . "## ") (end . "-->"))
    ("xml-mode"              (begin . "<!--") (mid . "## ") (end . "-->"))
    ("sgml-mode"             (begin . "<!--") (mid . "## ") (end . "-->"))
    ("web-mode"              (begin . "<!--") (mid . "## ") (end . "-->"))
    ("html-mode"             (begin . "<!--") (mid . "## ") (end . "-->"))
    ("vue-mode"              (begin . "<!--") (mid . "## ") (end . "-->"))
    ("php-mode"              (begin . "<?php\n/**") (mid . " ** ") (end . " */\n?>"))
    ("emacs-lisp-mode"       (begin . ";;; FILE_NAME_EXT --- -*- lexical-binding: t; -*-\n;;; package --- Summary\n;;; Commentary:") (mid . ";; ") (end . ";;; Code:\n\n\n(provide 'FILE_NAME)\n;;; FILE_NAME_EXT ends here"))
    ("lisp-mode"             (begin . ";;; FILE_NAME_EXT --- -*- lexical-binding: t; -*-\n;;; package --- Summary\n;;; Commentary:") (mid . ";; ") (end . ";;; Code:\n\n\n(provide 'FILE_NAME)\n;;; FILE_NAME_EXT ends here"))
    ("clojure-mode"          (begin . ";;")  (mid . ";; ") (end . ";;"))
    ("python-mode"           (begin . "##*") (mid . "## ") (end . "##"))
    ("makefile-gmake-mode"   (begin . "##*") (mid . "## ") (end . "## "))
    ("yaml-mode"             (begin . "##") (mid . "## ") (end . "##"))
    ("dockerfile-mode"       (begin . "##") (mid . "## ") (end . "##"))
    ("r-mode"                (begin . "##") (mid . "## ") (end . "##"))
    ("sh-mode"               (begin . "#!/bin/bash") (mid . "## ") (end . "## "))
    ("perl-mode"             (begin . "#!/usr/local/bin/perl -w") (mid . "## ") (end . "##"))
    ("ruby-mode"             (begin . "=begin") (mid . "## ") (end . "=end"))
    ("powershell-mode"       (begin . "<#") (mid . "## ") (end . "#>"))
    ("latex-mode"            (begin . "%%") (mid . "%% ") (end . "%%"))
    ("org-mode"              (begin . "#+BEGIN_COMMENT") (mid . "## ") (end . "#+END_COMMENT"))))
