#+BEGIN_COMMENT
## ======================================================================
## @license Copyright 2016-2025 Pierre Schebath
## ---------------------
## 
## @brief This file has been written by Pierre Etienne Charles Schebath Cazoulat.
## 
## This source code, its related data and algorithms are Pierre Schebath
## Proprietary Information and shall be protected in strict confidence by
## the party who receives it.  It shall not be disclosed nor copied nor
## duplicated in whole or in part to any third party without Pierre Schebath
## written prior permission.
## ======================================================================
## globals.org for revolution in ~/.emacs.d/revolution/
## @description: major mode manager
## 
## Started on  Wed Jun  4 23:45:47 2025 @author Glider
## Last update Mon Jan 26 08:08:31 2026 @author Glider
## ======================================================================
#+END_COMMENT

#+NAME: BOF_globals()
#+BEGIN_SRC emacs-lisp :lexical t

;;; globals.el --- -*- lexical-binding: t; -*-
;;; Commentary:
;;; Set config following the major mode
;;; code:

(defgroup emacs-revolution nil
  "Emacs Revolution."
  :group 'tools)

(defconst emacs-revolution-dir
  (expand-file-name "~/.emacs.d/revolution/")
  "Racine du projet Emacs-Revolution.")
    
#+END_SRC

#+NAME:lang_settings_globals()
#+BEGIN_SRC emacs-lisp :lexical t

(defcustom lang-settings-dir (expand-file-name "revolution/modes/" user-emacs-directory)
  "Dossier contenant les fichiers de configuration par langage."
  :type 'directory
  :group 'emacs-revolution)

(defcustom er-src-mode major-mode
  "Major mode source for Emacs-Revolution."
  :type 'symbol
  :group 'emacs-revolution)

(unless er-src-mode
  (setq er-src-mode major-mode))
    
#+END_SRC

#+NAME: std_modes_alist()
#+BEGIN_SRC emacs-lisp :lexical t

(defcustom std-modes-alist
  '(("c-mode"                (begin . "/**") (mid . " * ") (end . "**/"))
    ("c++-mode"              (begin . "/**") (mid . " * ") (end . " */"))
    ("css-mode"              (begin . "/**") (mid . " * ") (end . " */"))
    ("scss-mode"             (begin . "/**") (mid . " * ") (end . " */"))
    ("text-mode"             (begin . "/**") (mid . " * ") (end . " */"))
    ("javascript-mode"       (begin . "/**") (mid . " * ") (end . " */"))
    ("java-mode"             (begin . "/**") (mid . " * ") (end . "**/"))
    ("js-mode"               (begin . "/**") (mid . " * ") (end . "**/"))
    ("js2-mode"              (begin . "/**") (mid . " * ") (end . "**/"))
    ("js3-mode"              (begin . "/**") (mid . " * ") (end . "**/"))
    ("typescript-mode"       (begin . "/**") (mid . " * ") (end . " */"))
    ("go-mode"               (begin . "/*")  (mid . " * ") (end . " */"))
    ("scala-mode"            (begin . "/*")  (mid . " * ") (end . " */"))
    ("kotlin-mode"           (begin . "/*")  (mid . " * ") (end . " */"))
    ("swift-mode"            (begin . "/*")  (mid . " * ") (end . " */"))
    ("csharp-mode"           (begin . "/*")  (mid . " * ") (end . " */"))
    ("rust-mode"             (begin . "///") (mid . "/// ") (end . "///"))
    ("json-mode"             (begin . "//")  (mid . "// ") (end . "//"))
    ("mhtml-mode"            (begin . "<!--") (mid . "## ") (end . "-->"))
    ("xml-mode"              (begin . "<!--") (mid . "## ") (end . "-->"))
    ("sgml-mode"             (begin . "<!--") (mid . "## ") (end . "-->"))
    ("web-mode"              (begin . "<!--") (mid . "## ") (end . "-->"))
    ("html-mode"             (begin . "<!--") (mid . "## ") (end . "-->"))
    ("vue-mode"              (begin . "<!--") (mid . "## ") (end . "-->"))
    ("php-mode"              (begin . "<?php\n/**") (mid . " ** ") (end . " */\n?>"))
    ("emacs-lisp-mode"
     (begin . ";;; FILE_NAME_EXT --- -*- lexical-binding: t; -*-\n;;; package --- Summary\n;;; Commentary:")
     (mid . ";; ")
     (end . ";;; Code:\n\n\n(provide 'FILE_NAME)\n;;; FILE_NAME_EXT ends here"))
    ("lisp-mode"
     (begin . ";;; FILE_NAME_EXT --- -*- lexical-binding: t; -*-\n;;; package --- Summary\n;;; Commentary:")
     (mid . ";; ")
     (end . ";;; Code:\n\n\n(provide 'FILE_NAME)\n;;; FILE_NAME_EXT ends here"))
    ("clojure-mode"          (begin . ";;")  (mid . ";; ") (end . ";;"))
    ("python-mode"           (begin . "##*") (mid . "## ") (end . "##"))
    ("makefile-gmake-mode"   (begin . "##*") (mid . "## ") (end . "## "))
    ("yaml-mode"             (begin . "##") (mid . "## ") (end . "##"))
    ("fundamental-mode"      (begin . "##") (mid . "## ") (end . "##"))
    ("dockerfile-mode"       (begin . "##") (mid . "## ") (end . "##"))
    ("r-mode"                (begin . "##") (mid . "## ") (end . "##"))
    ("sh-mode"               (begin . "#!/bin/bash") (mid . "## ") (end . "## "))
    ("perl-mode"             (begin . "#!/usr/local/bin/perl -w") (mid . "## ") (end . "##"))
    ("ruby-mode"             (begin . "=begin") (mid . "## ") (end . "=end"))
    ("powershell-mode"       (begin . "<#") (mid . "## ") (end . "#>"))
    ("latex-mode"            (begin . "%%") (mid . "%% ") (end . "%%"))
    ("org-mode"              (begin . "#+BEGIN_COMMENT") (mid . "## ") (end . "#+END_COMMENT")))
  "Association entre major-modes et formats de commentaires standards.
Chaque entrée est de la forme :
  (MODE (begin . STRING) (mid . STRING) (end . STRING))."
  :type '(repeat
          (list
           (string :tag "Major mode name")
           (cons :tag "Begin" (const begin) string)
           (cons :tag "Middle" (const mid) string)
           (cons :tag "End" (const end) string)))
  :group 'emacs-revolution)

(defcustom mode-associations
  '(("\\.jsx?\\'"       . web-mode)
    ("\\.tsx?\\'"       . web-mode)
    ("\\.[agj]sp\\'"    . web-mode)
    ("\\.as[cp]x\\'"    . web-mode)
    ("\\.erb\\'"        . web-mode)
    ("\\.mustache\\'"   . web-mode)
    ("\\.djhtml\\'"     . html-mode)
    ("\\.html?\\'"      . html-mode)
    ("\\.phtml\\'"      . html-mode)
    ("\\.php\\'"        . php-mode)
    ("\\.js\\'"         . js2-mode)
    ("\\.json\\'"       . json-mode)
    ("\\.yaml\\'"       . yaml-mode)
    ("\\.yml\\'"        . yaml-mode)
    ("\\.conf\\'"       . conf-mode)
    ("\\.cfg\\'"        . conf-mode)
    ("\\.env\\'"        . conf-mode)
    ("\\.gitignore\\'"  . conf-mode)
    ("\\.htaccess\\'"   . conf-mode)
    ("\\.c\\'"          . c-mode)
    ("\\.h\\'"          . c-mode)
    ("\\.cpp\\'"        . c++-mode)
    ("\\.cc\\'"         . c++-mode)
    ("\\.cxx\\'"        . c++-mode)
    ("\\.hpp\\'"        . c++-mode)
    ("\\.glsl\\'"       . glsl-mode)
    ("\\.el\\'"         . emacs-lisp-mode)
    ("\\.lisp\\'"       . lisp-mode)
    ("\\.scm\\'"        . scheme-mode)
    ("\\.css\\'"        . css-mode)
    ("\\.org\\'"        . org-mode)
    ("\\.xml\\'"        . nxml-mode))
  "Associations entre extensions de fichiers et major-modes."
  :type '(repeat
          (cons
           (regexp :tag "Filename regexp")
           (symbol :tag "Major mode")))
  :group 'emacs-revolution)

#+END_SRC

#+NAME: EOF_globals()
#+BEGIN_SRC emacs-lisp :lexical t

(provide 'globals)
;;; globals.el ends here

#+END_SRC
