#+BEGIN_COMMENT
## ======================================================================
## @license Copyright 2016-2026 Pierre Schebath
## ---------------------
## 
## @brief This file has been written by Pierre Etienne Charles Schebath Cazoulat.
## 
## This source code, its related data and algorithms are Pierre Schebath
## Proprietary Information and shall be protected in strict confidence by
## the party who receives it.  It shall not be disclosed nor copied nor
## duplicated in whole or in part to any third party without Pierre Schebath
## written prior permission.
## ======================================================================
## attainment.org for Emacs Revolution in ~/.emacs.d/revolution/
## @description: Load attainment configuration for any major-mode.
## 
## Started on  Mon Jan 26 14:33:35 2026 @author Glider
## Last update Fri Apr 17 02:16:41 2026 @author Glider
## ======================================================================
#+END_COMMENT

* attainment of project

** Header
#+NAME: BOF_attainment
#+BEGIN_SRC emacs-lisp :lexical t

;;; ihm.el --- -*- lexical-binding: t; -*-
;;; Commentary:
;;; 
;;; Code:

#+END_SRC

** Disk Usage
#+NAME: Disk Uage
#+BEGIN_SRC emacs-lisp :lexical t

(use-package disk-usage :ensure t)

#+END_SRC

* Neotree
#+NAME: neotree
#+BEGIN_SRC emacs-lisp :lexical t

;; ===============================
;; neotree: File system explorer.
;; ===============================

(use-package neotree
  :ensure t
  :bind ([f8] . neotree-toggle)
  :config (setq neo-default-system-application "open")
  :init
  (setq neo-theme (if (display-graphic-p) 'icons 'arrow)))

#+END_SRC

* Dired
 Lets you select a file and then launch an external application with that file.
#+NAME: Dired
#+BEGIN_SRC emacs-lisp :lexical t

;; ===============================
;; Dired: Lets you select a file and then launch an external application with that file.
;; ===============================

(use-package dired-launch
  :ensure t
  :init
  (dired-launch-mode 1))

(use-package dired-quick-sort
  :ensure t
  :init
  (setq dired-quick-sort-suppress-setup-warning t)
  (dired-quick-sort-setup))

(use-package dired-filetype-face :ensure t)

#+END_SRC

#+NAME: Project
#+BEGIN_SRC emacs-lisp :lexical t

;;(use-package projection
;;   :ensure t
;;   ;; Enable the `projection-hook' feature.
;;   :hook (after-init . global-projection-hook-mode)
;;   ;; Enable the `projection-customize-compilation' feature.
;;   :hook (compilation-mode . projection-customize-compilation-mode)
;;   :custom
;;   (compilation-buffer-name-function
;;    #'projection-customize-compilation-buffer-name-function)
;;   ;; Require projections immediately after project.el.
;;   :config
;;   (with-eval-after-load 'project
;;     (require 'projection))
;;   :config
;;   ;; Uncomment if you want to disable prompts for compile commands customized in .dir-locals.el
;;   ;; (put 'projection-commands-configure-project 'safe-local-variable #'stringp)
;;   ;; (put 'projection-commands-build-project 'safe-local-variable #'stringp)
;;   ;; (put 'projection-commands-test-project 'safe-local-variable #'stringp)
;;   ;; (put 'projection-commands-run-project 'safe-local-variable #'stringp)
;;   ;; (put 'projection-commands-package-project 'safe-local-variable #'stringp)
;;   ;; (put 'projection-commands-install-project 'safe-local-variable #'stringp)

;;   ;; Access pre-configured projection commands from a keybinding of your choice.
;;   ;; Run `M-x describe-keymap projection-map` for a list of available commands.
;;   :bind-keymap
;;   ("C-x P" . projection-map))

;; (use-package projection-multi
;;   :ensure t
;;   ;; Allow interactively selecting available compilation targets from the current
;;   ;; project type.
;;   :bind ( :map project-prefix-map
;;           ("RET" . projection-multi-compile)))

;; (use-package embark-consult :ensure t)

;; (use-package projection-multi-embark
;;   :ensure t
;;   :after embark
;;   :after projection-multi
;;   :demand t
;;   ;; Add the projection set-command bindings to `compile-multi-embark-command-map'.
;;   :config (projection-multi-embark-setup-command-map))

;; (use-package consult
;;   :ensure t)

;; (consult-customize
;;  consult-ripgrep consult-git-grep consult-grep consult-man
;;  consult-bookmark consult-recent-file consult-xref
;;  consult-source-bookmark consult-source-file-register
;;  consult-source-recent-file consult-source-project-recent-file
;;  :preview-key '(:debounce 0.4 any))

;; (defvar consult-source-bookmark
;;   `(:name     "Bookmark"
;;     :narrow   ?m
;;     :category bookmark
;;     :face     consult-bookmark
;;     :history  bookmark-history
;;     :items    ,#'bookmark-all-names
;;     :action   ,#'consult--bookmark-action))



;; (use-package consult-project-extra
;;   :ensure t
;;   :custom (consult-project-function #'consult-project-extra-project-fn) ;; Optional but recommended for a more consistent UI
;;   :bind
;;   (("C-c p f" . consult-project-extra-find)
;;    ("C-c p o" . consult-project-extra-find-other-window)))

#+END_SRC


** Surround a string
#+NAME: unicode-enbox
#+BEGIN_SRC emacs-lisp :lexical t

;; (use-package unicode-enbox
;;   :ensure t
;;   :init
;;   (set-fontset-font "fontset-default"
;;                   (cons (decode-char 'ucs #x2500)  (decode-char 'ucs #x257F))
;;                   (font-spec :name "DejaVu Sans Mono:" :registry "iso10646-1")))

#+END_SRC

* End Of File
#+NAME: BOF_attainment
#+BEGIN_SRC emacs-lisp :lexical t

(provide 'attainment)
;;; attainment.el ends here

#+END_SRC
