#+BEGIN_COMMENT
## ======================================================================
## @license Copyright 2016-2026 Pierre Schebath
## ---------------------
## 
## @brief This file has been written by Pierre Etienne Charles Schebath Cazoulat.
## 
## This source code, its related data and algorithms are Pierre Schebath
## Proprietary Information and shall be protected in strict confidence by
## the party who receives it.  It shall not be disclosed nor copied nor
## duplicated in whole or in part to any third party without Pierre Schebath
## written prior permission.
## ======================================================================
## attainment.org for Emacs Revolution in ~/.emacs.d/revolution/
## @description: Load attainment configuration for any major-mode.
## 
## Started on  Mon Jan 26 14:33:35 2026 @author Glider
## Last update Thu Apr 23 08:49:55 2026 @author Glider
## ======================================================================
#+END_COMMENT

* attainment of project

** Header
#+NAME: BOF_attainment
#+BEGIN_SRC emacs-lisp :lexical t

;;; ihm.el --- -*- lexical-binding: t; -*-
;;; Commentary:
;;; 
;;; Code:

#+END_SRC

** Disk Usage & Project
#+NAME: Disk Uage & Project
#+BEGIN_SRC emacs-lisp :lexical t

(use-package disk-usage :ensure t)

(use-package projectile :ensure t)
(use-package helm-project :ensure t)
(use-package helm-projectile :ensure t)

#+END_SRC

** Neotree
#+NAME: neotree
#+BEGIN_SRC emacs-lisp :lexical t

;; ===============================
;; neotree: File system explorer.
;; ===============================

(use-package neotree
  :ensure t
  :bind ([f8] . neotree-toggle)
  :config (setq neo-default-system-application "open")
  :init
  (setq neo-theme (if (display-graphic-p) 'icons 'arrow)))

#+END_SRC

** Dired
 Lets you select a file and then launch an external application with that file.
#+NAME: Dired
#+BEGIN_SRC emacs-lisp :lexical t

;; ===============================
;; Dired: Lets you select a file and then launch an external application with that file.
;; ===============================

(use-package dired-launch
  :ensure t
  :init
  (dired-launch-mode 1))

(use-package dired-quick-sort
  :ensure t
  :init
  (setq dired-quick-sort-suppress-setup-warning t)
  (dired-quick-sort-setup))

(use-package dired-filetype-face :ensure t)

#+END_SRC

** Flycheck
#+NAME: Flycheck
#+BEGIN_SRC emacs-lisp :lexical t

;; ================================================================
;; Flycheck 
;; ================================================================
(use-package flycheck
  :ensure t
  :after php-mode
  :config
  (global-flycheck-mode)
  (flycheck-title-mode))

#+END_SRC

** Orderless
#+NAME: Orderless
#+BEGIN_SRC emacs-lisp :lexical t

;; ===============================
;; Orderless
;; ===============================
(use-package orderless
  :ensure t
  :custom
  (orderless-matching-styles '(orderless-prefixes))
  (orderless-component-separator 'orderless-escapable-split-on-space)
  (read-file-name-completion-ignore-case t)
  (read-buffer-completion-ignore-case t)
  (completion-ignore-case nil)
  (completion-category-defaults nil)
  (completion-category-overrides '((file (styles basic partial-completion))))
  :config (message "`orderless' loaded"))

#+END_SRC

** Research
#+NAME: Research
#+BEGIN_SRC emacs-lisp :lexical t

;; ===============================
;; Research
;; ===============================
(use-package ace-isearch
  :ensure t
  :config
  (global-ace-isearch-mode +1)
  (setq ace-jump-word-mode t
	helm-multi-swoop-projectile t)
  (setq ace-isearch-function-from-isearch 'helm-occur-from-isearch))

#+END_SRC

** Highlight Symbols, Selections, Enclosing Parens and More
#+NAME: unicode-enbox
#+BEGIN_SRC emacs-lisp :lexical t

(use-package hl-anything
  :ensure t
  :config
  (hl-line-mode)
  (global-hl-line-mode)
  (hl-highlight-thingatpt-global)
  (hl-highlight-thingatpt-local))


(use-package highlight-indent-guides
  :ensure t
  :config (highlight-indent-guides-mode))

;; (use-package unicode-enbox
;;   :ensure t
;;   :init
;;   (set-fontset-font "fontset-default"
;;                   (cons (decode-char 'ucs #x2500)  (decode-char 'ucs #x257F))
;;                   (font-spec :name "DejaVu Sans Mono:" :registry "iso10646-1")))

#+END_SRC

* End Of File
#+NAME: BOF_attainment
#+BEGIN_SRC emacs-lisp :lexical t

(provide 'attainment)
;;; attainment.el ends here

#+END_SRC
