;;; boxy-headings-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from boxy-headings.el

(autoload 'boxy-headings "boxy-headings" "\
View all org headings as a boxy diagram." t)
(register-definition-prefixes "boxy-headings" '("boxy-headings-"))

;;; End of scraped data

(provide 'boxy-headings-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; boxy-headings-autoloads.el ends here
